// Dated terms are career-owned; weekly wages remain part of the Monday payroll.
const days=(a,b)=>Math.floor((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000);
export function contractEnd(c,p){return c.contracts?.[p.id]?.end||`${Number((c.seasonStart||c.date).slice(0,4))+Math.max(1,Math.min(5,p.contract||1))}-06-30`}
export function initialiseContracts(c,league){c.contracts??={};for(const p of league.players)if(!c.contracts[p.id])c.contracts[p.id]={end:contractEnd(c,p)};}
export function contractStatus(c,p){const end=contractEnd(c,p),remaining=days(c.date,end),seasonEnd=`${Number((c.seasonStart||c.date).slice(0,4))+1}-06-30`;return {end,days:remaining,expiring:end<=seasonEnd,rolling:remaining<0};}
export function renewalDemand(c,p,years){const state=c.players[p.id]||{},base=Math.max(p.wage,Math.round((p.overall-55)**2*15));const increase=(state.happiness<35?.15:.05)+(years>=3?.05:0);return Math.ceil(base*(1+increase)/50)*50;}
export function renewContract(c,league,id,wage,years){const p=league.players.find(p=>p.id===id),owned=p&&(c.owners?.[id]||p.clubId)===c.clubId;if(!owned||c.players[id]?.retired)return {error:'This player is no longer at your club.'};if(!Number.isInteger(years)||years<1||years>4||!Number.isFinite(wage)||wage<50||wage>1000000||wage%50!==0)return {error:'Choose 1–4 years and a weekly wage in steps of £50.'};const demand=renewalDemand(c,p,years);if(wage<demand)return {error:`Player counter: £${demand.toLocaleString('en-GB')}/week for ${years} year${years===1?'':'s'}.`,demand};initialiseContracts(c,league);const end=`${Number(c.date.slice(0,4))+(c.date.slice(5)>='06-30'?1:0)+years-1}-06-30`,previous=p.wage;p.wage=wage;p.contract=years;c.contracts[id]={end};c.playerChanges??={};c.playerChanges[id]={...(c.playerChanges[id]||{}),wage,contract:years};const generated=c.generatedPlayers?.find(x=>x.id===id);if(generated){generated.wage=wage;generated.contract=years;}c.news.push({date:c.date,kind:'contract-renewal',text:`${p.name} renewed until ${end}: £${wage.toLocaleString('en-GB')}/week (${wage>=previous?'+':''}£${(wage-previous).toLocaleString('en-GB')}/week).`});return {end,wage,previous};}
export function contractReminders(c,players,offSeason){c.contractReminderKeys??=[];const expiring=players.filter(p=>contractStatus(c,p).expiring),due=expiring.filter(p=>offSeason||contractStatus(c,p).days<=90);if(!due.length)return;const key=`${c.season}:${offSeason?'off-season':'90-days'}`;if(c.contractReminderKeys.includes(key))return;c.contractReminderKeys.push(key);c.news.push({date:c.date,kind:'contracts',action:'contracts',text:`${offSeason?'Off-season contract review':'Contract expiry warning'}: ${due.length} player${due.length===1?'':'s'} ${due.length===1?'needs':'need'} a renewal decision. Review weekly wages and terms in Finances → Contracts.`});}
export function squadCover(c,players,slots){const available=p=>!c.players[p.id]?.injuryDays&&!c.players[p.id]?.suspensionMatches&&!c.players[p.id]?.retired&&!c.players[p.id]?.unregistered&&!c.loans?.[p.id],suits=(p,pos)=>pos==='GK'?p.primary==='GK':p.primary!=='GK'&&(p.positions[pos]||0)/p.overall>=.75;const pool=players.filter(available),assigned=new Map();function fill(i,seen){for(const p of pool.filter(p=>suits(p,slots[i])).sort((a,b)=>(b.positions[slots[i]]||0)-(a.positions[slots[i]]||0))){if(seen.has(p.id))continue;seen.add(p.id);if(!assigned.has(p.id)||fill(assigned.get(p.id),seen)){assigned.set(p.id,i);return true}}return false}slots.forEach((_,i)=>fill(i,new Set()));return {filled:assigned.size,total:slots.length,rows:[...new Set(slots)].map(pos=>{const need=slots.filter(x=>x===pos).length,options=players.filter(p=>suits(p,pos)),fit=options.filter(available),expiring=options.filter(p=>contractStatus(c,p).expiring);return {pos,need,available:fit,unavailable:options.filter(p=>!available(p)),expiring,status:fit.length<need?'short':fit.length===need?'thin':'covered'}})};}
