import {playerValue} from './transfer-search.js?v=1.49.0';
import {scoutEstimate} from './scouting.js?v=1.49.0';
import {contractStatus,squadCover} from './contracts.js?v=1.49.0';
export const estimatedBid=p=>Math.round(playerValue(p)*1.1/10000)*10000;
const owner=(c,p)=>c.owners?.[p.id]||p.clubId;
const active=(c,p)=>!c.players?.[p.id]?.retired&&!c.players?.[p.id]?.unregistered;
const ready=(c,p)=>active(c,p)&&!c.players?.[p.id]?.injuryDays&&!c.players?.[p.id]?.suspensionMatches&&!c.loans?.[p.id];
export const suitsRole=(p,pos)=>pos==='GK'?p.primary==='GK':p.primary!=='GK'&&(pos===p.primary?1:(p.positions?.[pos]||0)/p.overall)>=.75;
const ratio=(p,pos)=>pos===p.primary?1:(p.positions?.[pos]||0)/p.overall;
export function signingAssessment(c,players,slots,p,key,requestedRole){const own=players.filter(x=>owner(c,x)===c.clubId&&active(c,x)&&x.id!==p.id),cover=squadCover(c,own,slots),estimate=scoutEstimate(p,c.scoutingFunding||0,key),roles=cover.rows.filter(r=>suitsRole(p,r.pos)),rank=r=>(r.status==='short'?100:r.status==='thin'?50:r.expiring.length?20:0)+estimate.centre*ratio(p,r.pos)-Math.max(0,...r.available.map(x=>x.overall*ratio(x,r.pos)));const row=roles.find(r=>r.pos===requestedRole)||roles.sort((a,b)=>rank(b)-rank(a))[0],role=row?.pos||p.primary,peers=own.filter(x=>suitsRole(x,role)).sort((a,b)=>b.overall*ratio(b,role)-a.overall*ratio(a,role)),available=peers.filter(x=>ready(c,x)),best=available[0],low=Math.round(estimate.low*ratio(p,role)),high=Math.round(estimate.high*ratio(p,role)),current=best?Math.round(best.overall*ratio(best,role)):0,upgrade=best?(low>current?'likely-upgrade':high<current?'cover':'uncertain'):'new-option';return {role,row,peers:peers.slice(0,3),available:available.length,low,high,current,best,upgrade,estimate,score:row?rank(row):0,weekly:own.reduce((n,p)=>n+p.wage,0)};}
export function recruitmentRecommendations(c,players,slots,key,position='priority'){const own=players.filter(p=>owner(c,p)===c.clubId&&active(c,p)),cover=squadCover(c,own,slots),needs=cover.rows.filter(r=>r.status!=='covered'||r.expiring.length),counts=new Map();for(const p of players.filter(p=>active(c,p)))counts.set(owner(c,p),(counts.get(owner(c,p))||0)+1);const weekly=own.reduce((n,p)=>n+p.wage,0);const result=[];for(const p of players){if(owner(c,p)===c.clubId||!ready(c,p)||(counts.get(owner(c,p))||0)<=18)continue;const fee=estimatedBid(p),reserve=4*(weekly+p.wage);if(c.balance-fee<reserve)continue;const roles=position==='priority'?needs.filter(r=>suitsRole(p,r.pos)).map(r=>r.pos):suitsRole(p,position)?[position]:[];if(!roles.length)continue;const assessment=roles.map(role=>signingAssessment(c,players,slots,p,key,role)).sort((a,b)=>b.score-a.score)[0];result.push({p,fee,reserve,afterReserve:c.balance-fee-reserve,assessment});}return {needs,weekly,rows:result.sort((a,b)=>b.assessment.score-a.assessment.score||a.fee-b.fee||a.p.id.localeCompare(b.p.id)).slice(0,5)};}
// Sale advice uses only registered club players; academy-only ability stays hidden.
export function saleAssessment(c,players,slots,p,fee){
 const own=players.filter(x=>owner(c,x)===c.clubId&&active(c,x)),remaining=own.filter(x=>x.id!==p.id),before=squadCover(c,own,slots),after=squadCover(c,remaining,slots),role=p.primary,peers=remaining.filter(x=>suitsRole(x,role)).sort((a,b)=>b.overall*ratio(b,role)-a.overall*ratio(a,role)),available=peers.filter(x=>ready(c,x)),best=available[0],young=available.filter(x=>x.age<=23&&x.age<p.age&&x.overall*ratio(x,role)>=p.overall-5).sort((a,b)=>b.overall*ratio(b,role)-a.overall*ratio(a,role))[0],value=playerValue(p),offerRatio=value>0?fee/value:1,roleRows=after.rows.filter(r=>suitsRole(p,r.pos)),risk=after.filled<before.filled||slots.includes(role)&&!available.length||roleRows.some(r=>r.status==='short'),thin=roleRows.some(r=>r.status==='thin'),weekly=own.reduce((n,x)=>n+x.wage,0),cash=c.balance+fee,reserve=4*(weekly-p.wage),form=c.players?.[p.id]?.form?.slice(-5)||[],average=form.length?form.reduce((a,b)=>a+b,0)/form.length:null;
 const reasons=[];let verdict='Review the price',tone='amber';
 if(own.length<=18){verdict='Keep until a replacement arrives';tone='red';reasons.push('This sale would leave fewer than 18 registered players; the game will not allow it.');}
 else if(risk){verdict='Arrange cover before selling';tone='red';reasons.push(`Available formation cover falls from ${before.filled}/${before.total} to ${after.filled}/${after.total}, or this removes essential positional cover.`);}
 else if(offerRatio<.9){verdict='Ask for a stronger offer';reasons.push('The fee is below 90% of our estimated value. Consider a counter-offer.');}
 else if(young&&offerRatio>=1){verdict='Consider accepting';tone='green';reasons.push(`${young.name} (${young.age}) is available and within five effective ability points in ${role}. Selling could create more first-team opportunities.`);}
 else if(best&&best.overall*ratio(best,role)>=p.overall&&offerRatio>=1){verdict='Consider accepting';tone='green';reasons.push(`${best.name} provides available cover at least as strong in ${role}.`);}
 else if(offerRatio>=1.15&&!thin){verdict='Worth considering';tone='green';reasons.push('The offer is at least 15% above estimated value, while the current formation remains covered.');}
 else {verdict='Weigh the squad impact';reasons.push(best?`${best.name} is your strongest available alternative in ${role}. Compare the quality gap before agreeing.`:'There is no available like-for-like replacement.');}
 if(!roleRows.length)reasons.push('He does not cover a position used in the current formation. Reconsider if you plan to change shape.');
 if(contractStatus(c,p).expiring)reasons.push('His contract expires this season. Compare this fee with the cost of a renewal.');
 if(thin)reasons.push('Some affected formation roles would have no spare available player after this sale.');
 if(cash<reserve)reasons.push('Even after this fee, cash would cover fewer than four weekly payrolls.');
 if(average!==null&&average>=7.3)reasons.push(`Recent form averages ${average.toFixed(1)}; losing an in-form player may disrupt results.`);
 return {verdict,tone,reasons,before,after,peers,available,best,young,offerRatio,value,weekly,cash,reserve};
}
