import {playerValue} from './transfer-search.js?v=1.44.0';
import {scoutEstimate} from './scouting.js?v=1.44.0';
import {squadCover} from './contracts.js?v=1.44.0';
export const estimatedBid=p=>Math.round(playerValue(p)*1.1/10000)*10000;
const owner=(c,p)=>c.owners?.[p.id]||p.clubId;
const active=(c,p)=>!c.players?.[p.id]?.retired&&!c.players?.[p.id]?.unregistered;
const ready=(c,p)=>active(c,p)&&!c.players?.[p.id]?.injuryDays&&!c.players?.[p.id]?.suspensionMatches&&!c.loans?.[p.id];
export const suitsRole=(p,pos)=>pos==='GK'?p.primary==='GK':p.primary!=='GK'&&(pos===p.primary?1:(p.positions?.[pos]||0)/p.overall)>=.75;
const ratio=(p,pos)=>pos===p.primary?1:(p.positions?.[pos]||0)/p.overall;
export function signingAssessment(c,players,slots,p,key,requestedRole){const own=players.filter(x=>owner(c,x)===c.clubId&&active(c,x)&&x.id!==p.id),cover=squadCover(c,own,slots),estimate=scoutEstimate(p,c.scoutingFunding||0,key),roles=cover.rows.filter(r=>suitsRole(p,r.pos)),rank=r=>(r.status==='short'?100:r.status==='thin'?50:r.expiring.length?20:0)+estimate.centre*ratio(p,r.pos)-Math.max(0,...r.available.map(x=>x.overall*ratio(x,r.pos)));const row=roles.find(r=>r.pos===requestedRole)||roles.sort((a,b)=>rank(b)-rank(a))[0],role=row?.pos||p.primary,peers=own.filter(x=>suitsRole(x,role)).sort((a,b)=>b.overall*ratio(b,role)-a.overall*ratio(a,role)),available=peers.filter(x=>ready(c,x)),best=available[0],low=Math.round(estimate.low*ratio(p,role)),high=Math.round(estimate.high*ratio(p,role)),current=best?Math.round(best.overall*ratio(best,role)):0,upgrade=best?(low>current?'likely-upgrade':high<current?'cover':'uncertain'):'new-option';return {role,row,peers:peers.slice(0,3),available:available.length,low,high,current,best,upgrade,estimate,score:row?rank(row):0,weekly:own.reduce((n,p)=>n+p.wage,0)};}
export function recruitmentRecommendations(c,players,slots,key,position='priority'){const own=players.filter(p=>owner(c,p)===c.clubId&&active(c,p)),cover=squadCover(c,own,slots),needs=cover.rows.filter(r=>r.status!=='covered'||r.expiring.length),counts=new Map();for(const p of players.filter(p=>active(c,p)))counts.set(owner(c,p),(counts.get(owner(c,p))||0)+1);const weekly=own.reduce((n,p)=>n+p.wage,0);const result=[];for(const p of players){if(owner(c,p)===c.clubId||!ready(c,p)||(counts.get(owner(c,p))||0)<=18)continue;const fee=estimatedBid(p),reserve=4*(weekly+p.wage);if(c.balance-fee<reserve)continue;const roles=position==='priority'?needs.filter(r=>suitsRole(p,r.pos)).map(r=>r.pos):suitsRole(p,position)?[position]:[];if(!roles.length)continue;const assessment=roles.map(role=>signingAssessment(c,players,slots,p,key,role)).sort((a,b)=>b.score-a.score)[0];result.push({p,fee,reserve,afterReserve:c.balance-fee-reserve,assessment});}return {needs,weekly,rows:result.sort((a,b)=>b.assessment.score-a.assessment.score||a.fee-b.fee||a.p.id.localeCompare(b.p.id)).slice(0,5)};}
