// Senior training: saved choices, modest daily effects, and weekly summaries.
export const TRAINING_MODES=['Balanced','Fitness','Development'];
export const TRAINING_POSITIONS=['GK','LB','CB','RB','DM','CM','AM','LW','RW','ST'];
const elapsed=(a,b)=>Math.floor((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000);
const owned=(c,p)=>(c.owners?.[p.id]||p.clubId)===c.clubId&&!c.players?.[p.id]?.retired&&!c.players?.[p.id]?.unregistered;
const snapshot=(c,players)=>Object.fromEntries(players.filter(p=>owned(c,p)).map(p=>[p.id,{overall:p.overall,fitness:c.players[p.id].fitness,positions:{...p.positions}}]));
export function initialiseTraining(c,league){c.training??={};const t=c.training;if(!TRAINING_MODES.includes(t.mode))t.mode='Balanced';t.assistant=!!t.assistant;t.assignments??={};t.recentDays??=[];t.reports??=[];t.lastDay??=c.date;t.lastReportDate??=c.date;t.baseline??=snapshot(c,league.players);t.focusDays??={Balanced:0,Fitness:0,Development:0};return t;}
export function trainingMode(c,league,next){const t=c.training||{};if(!t.assistant)return TRAINING_MODES.includes(t.mode)?t.mode:'Balanced';const selected=new Set(c.lineup||[]),active=league.players.filter(p=>owned(c,p)&&!c.players[p.id].injuryDays),xi=active.filter(p=>selected.has(p.id)),pool=xi.length?xi:active,average=pool.length?pool.reduce((n,p)=>n+c.players[p.id].fitness,0)/pool.length:100,days=next?elapsed(c.date,next.date):Infinity;if(average<85||days<=2)return 'Fitness';if(days>=4&&active.filter(p=>p.age<=24&&p.overall<p.potential).length>=3)return 'Development';return 'Balanced';}
export function trainingModifiers(c,league,next){const mode=c.training?.dayModeDate===c.date?c.training.dayMode:trainingMode(c,league,next);return {mode,development:mode==='Fitness'?.75:mode==='Development'?1.35:1,recovery:mode==='Fitness'?1:mode==='Development'?-1:0};}
export function beginTrainingDay(c,league,next){const t=initialiseTraining(c,league);if(t.dayModeDate!==c.date){t.dayMode=trainingMode(c,league,next);t.dayModeDate=c.date;}if(t.recentDays.at(-1)?.date!==c.date){t.recentDays.push({date:c.date,mode:t.dayMode});t.recentDays=t.recentDays.slice(-7);}return trainingModifiers(c,league,next);}
export function setPositionTraining(c,league,id,position){const p=league.players.find(x=>x.id===id);if(!p||!owned(c,p))return false;if(position&&(!TRAINING_POSITIONS.includes(position)||position===p.primary||position==='GK'||p.primary==='GK'))return false;const t=initialiseTraining(c,league);if(!position){delete t.assignments[id];return true;}if(t.assignments[id]?.position!==position)t.assignments[id]={position,progress:0};return true;}
export function trainingDay(c,league,next){const t=initialiseTraining(c,league);if(t.lastDay===c.date)return;const modifiers=trainingModifiers(c,league,next);t.lastDay=c.date;t.focusDays[modifiers.mode]=(t.focusDays[modifiers.mode]||0)+1;const facilities=league.clubs.find(x=>x.id===c.clubId)?.facilities||1;for(const [id,a]of Object.entries(t.assignments)){const p=league.players.find(x=>x.id===id);if(!p||!owned(c,p)||c.players[id].injuryDays>0||p.primary==='GK'||a.position==='GK'||a.position===p.primary)continue;const cap=Math.ceil(p.overall*.9);if((p.positions[a.position]||0)>=cap){a.progress=0;continue;}a.progress=(a.progress||0)+(.025+facilities*.005)*modifiers.development*(p.age<=24?1.15:1);if(a.progress>=1){p.positions[a.position]=Math.min(cap,(p.positions[a.position]||0)+1);a.progress-=1;c.playerChanges??={};c.playerChanges[id]={...(c.playerChanges[id]||{}),positions:{...p.positions}};}}
 if(elapsed(t.lastReportDate,c.date)<7)return;const rows=league.players.filter(p=>owned(c,p)).map(p=>{const s=c.players[p.id],old=t.baseline[p.id],a=t.assignments[p.id],changes=old?TRAINING_POSITIONS.filter(pos=>(p.positions[pos]||0)!==(old.positions[pos]||0)).map(position=>({position,delta:(p.positions[position]||0)-(old.positions[position]||0)})):[];return {id:p.id,name:p.name,overall:p.overall,delta:old?p.overall-old.overall:0,condition:s.fitness,conditionChange:old?s.fitness-old.fitness:0,injuryDays:s.injuryDays||0,position:a?.position||null,positionReached:!!a&&(p.positions[a.position]||0)>=Math.ceil(p.overall*.9),progress:a?Math.min(99,Math.floor((a.progress||0)*100)):0,positionChanges:changes};});const report={date:c.date,focusDays:{...t.focusDays},rows};t.reports.push(report);t.reports=t.reports.slice(-12);t.lastReportDate=c.date;t.baseline=snapshot(c,league.players);t.focusDays={Balanced:0,Fitness:0,Development:0};c.news.push({date:c.date,kind:'training',action:'training',text:'Weekly training report: review confirmed changes, condition and positional practice in Squad → Training.'});}

export function trainingDevelopmentFactor(c,league,next){const days=c.training?.recentDays||[];return days.length?days.reduce((n,d)=>n+(d.mode==='Fitness'?.75:d.mode==='Development'?1.35:1),0)/days.length:trainingModifiers(c,league,next).development;}
