import assert from 'node:assert/strict';import {exteriorPeople} from '../stadium-life.js';
// Scene bounds include a 1.1-unit circulation setback; arrivals can approach within it.
const bounds={left:5,right:67,top:5,bottom:55},project=p=>({x:p.x*7.2-p.y*7.35,y:p.x*4.2+p.y*4.2-p.z*2.55}),render=phase=>{const r=exteriorPeople(project,phase,bounds);return r.far+r.near},idle=render('idle'),pre=render('prematch'),live=render('live'),post=render('postmatch'),count=(s,key)=>(s.match(new RegExp(key,'g'))||[]).length;
assert(count(pre,'class="stadium-walker"')>count(idle,'class="stadium-walker"')*4);assert(count(live,'class="stadium-walker"')<count(idle,'class="stadium-walker"'));assert(count(post,'class="stadium-walker"')>count(idle,'class="stadium-walker"'));assert(!idle.includes('matchday-stall'));for(const s of [pre,live,post])assert.equal(count(s,'class="matchday-stall"'),8);assert(!live.includes('stadium-queue'));assert(pre.includes('stadium-queue'));assert(pre.includes('data-walk-kind="arrival"'));assert(post.includes('data-walk-kind="departure"'));
const stallIds=s=>[...s.matchAll(/data-stall-id="([^"]+)"/g)].map(m=>m[1]);assert.deepEqual(stallIds(pre),stallIds(live));assert.deepEqual(stallIds(live),stallIds(post));
for(const s of [idle,pre,live,post]){assert(!/NaN|undefined|Infinity/.test(s));for(const m of s.matchAll(/data-walk-side="(\d)" data-walk-points='([^']+)'/g)){const side=Number(m[1]),points=JSON.parse(m[2]);for(const p of points){if(side===0)assert(p.y<bounds.top+1.0);if(side===1)assert(p.x>bounds.right-1.0);if(side===2)assert(p.y>bounds.bottom-1.0);if(side===3)assert(p.x<bounds.left+1.0)}const axis=side%2?'x':'y';assert(new Set(points.map(p=>p[axis].toFixed(3))).size>2,'Routes change distance from the stand');}assert(s.includes('Q'),'Curved wandering paths');assert(s.includes('keyPoints="0;.18;.18;'),'Routes include pauses');}
console.log('Quiet/arrival/live/departure densities, eight persistent stalls, queues, curved routes with pauses and stand clearance passed');

assert(pre.includes('data-stall-visit="true"'),'Pre-match visitors stop at stalls');assert(!live.includes('data-stall-visit="true"'),'Live exterior stays sparse');for(const side of [0,1,2,3])assert(new RegExp('data-walk-side="'+side+'"[^>]*data-stall-visit="true"').test(pre),'Stall visitors on each side');
