import {createRequire} from 'node:module';import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=new URL('../',import.meta.url).pathname.replace(/\/$/,''),results=[],errors=[],missing=[];
const hook=`\nglobalThis.__pilotTest={newClub(id){setup={clubId:id,site:'aberdeen',names:{},colour:null};newCareer();},info(){return {club:career?.clubId,site:career?.site,date:career?.date,rounds:career?.schedule.length,phase:match?.phase};},reloadSave(){load();view='career';render();},homeMatch(){career.friendlyInvitations=[];const next=nextFixture();career.date=next.date;career.time='09:00';advance();if(match.home!==career.clubId){[match.home,match.away]=[match.away,match.home];}beginMatch('watch');},pause(){match.paused=true;render();clearInterval(timer);},event(type){match.events.push({type,team:match.home,minute:match.minute,text:type+' integration check'});if(type==='goal')match.homeGoals++;match.flash={type,team:match.home,text:type+' integration check',minute:match.minute};save();render();},step(){simulateMinute();render();},title(){view='title';render();},nextTitle(){advanceTitleScene();},legacySite(){career.site='aberdeen';save();}};`;
const server=http.createServer((req,res)=>{let f=root+decodeURIComponent(req.url.split('?')[0]);if(f.endsWith('/'))f+='index.html';try{const ext=f.split('.').at(-1);res.setHeader('Content-Type',({js:'application/javascript',json:'application/json',html:'text/html',css:'text/css',webp:'image/webp',png:'image/png',svg:'image/svg+xml',webmanifest:'application/manifest+json'})[ext]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{missing.push(req.url);res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8765,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.CLUBLINE_CHROME_EXECUTABLE?{executablePath:process.env.CLUBLINE_CHROME_EXECUTABLE}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});await page.route('**/app.js*',async route=>route.fulfill({contentType:'application/javascript',body:fs.readFileSync(root+'/app.js','utf8')+hook}));
try{
await page.goto('http://127.0.0.1:8765');await page.waitForSelector('[data-action="new-game"]');await page.waitForTimeout(1900);await page.screenshot({path:root+'/review/title-portrait.png'});results.push('Title starts with live Highfield stadium and two scenery layers.');
await page.click('[data-action="new-game"]');assert.equal(await page.locator('[data-site]').count(),0);assert.match(await page.locator('body').innerText(),/Fixed club neighbourhood/);results.push('Pilot club setup has no location selector.');
for(const [id,name]of[['C01','Highfield'],['C13','Riverbank'],['C02','Vale-Park']]){
 await page.evaluate(id=>__pilotTest.newClub(id),id);console.log('career',id, await page.evaluate(()=>__pilotTest.info()),await page.locator('svg[data-fixed-surroundings]').count(),errors);let info=await page.evaluate(()=>__pilotTest.info());assert.equal(info.club,id);assert.equal(info.site,'fixed-'+id.toLowerCase());assert.equal(info.date,'1998-08-03');assert.equal(info.rounds,38);
 for(const [mode,w,h]of[['portrait',390,844],['landscape',844,390],['small-portrait',360,640]]){
 await page.setViewportSize({width:w,height:h});await page.waitForTimeout(200);await page.waitForFunction(()=>[...document.querySelectorAll('svg[data-fixed-surroundings] [data-surroundings-layer]')].length===2);assert.equal(await page.locator('.career-screen>.scene svg[data-fixed-surroundings]').getAttribute('data-fixed-surroundings'),id);
 const bounds=await page.evaluate(()=>{const s=document.querySelector('.career-screen>.scene svg'),r=s.getBoundingClientRect(),[cx,cy,fw,fh]=s.dataset.careerFrame.split(' ').map(Number),b=s.viewBox.baseVal;return{width:r.width,height:r.height,fit:fw<=b.width&&fh<=b.height,overflow:document.documentElement.scrollWidth>innerWidth};});assert(bounds.fit);assert(!bounds.overflow);
 await page.screenshot({path:root+`/review/${name}-${mode}.png`});
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__pilotTest.reloadSave());assert.equal(await page.locator('.career-screen>.scene svg').getAttribute('data-fixed-surroundings'),id);results.push(name+': career framing fits at 390×844, 844×390 and 360×640; save reload keeps fixed scene.');
 await page.evaluate(()=>__pilotTest.homeMatch());await page.click('[data-action="confirm-lineup"]');await page.evaluate(()=>__pilotTest.pause());await page.click('[data-action="match-view"]');assert.equal(await page.locator('.live-stage svg').getAttribute('data-fixed-surroundings'),id);await page.evaluate(()=>{globalThis.__originalStage=document.querySelector('.live-stage svg');globalThis.__originalLayers=[...__originalStage.querySelectorAll('[data-surroundings-layer]')];});
 for(const type of ['goal','yellow','half']){await page.evaluate(type=>__pilotTest.event(type),type);assert(await page.evaluate(()=>__originalStage===document.querySelector('.live-stage svg')&&__originalLayers.every((n,i)=>n===__originalStage.querySelectorAll('[data-surroundings-layer]')[i])));}
 await page.screenshot({path:root+`/review/${name}-match-portrait.png`});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(200);await page.screenshot({path:root+`/review/${name}-match-landscape.png`});results.push(name+': watched home match retains the identical live SVG and scenery image elements through goal, card and info refreshes.');
}
await page.evaluate(()=>__pilotTest.newClub('C03'));assert.equal(await page.locator('.career-screen>.scene svg[data-fixed-surroundings]').count(),0);results.push('Non-pilot C03 retains the original scene.');
await page.evaluate(()=>__pilotTest.newClub('C01'));await page.evaluate(async()=>{const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;});await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await page.unroute('**/app.js*');await page.reload();await page.waitForSelector('[data-action="continue"]');await page.click('[data-action="continue"]');await page.waitForTimeout(500);await page.context().setOffline(true);await page.reload();await page.waitForSelector('[data-action="continue"]');await page.click('[data-action="continue"]');assert.equal(await page.locator('.career-screen>.scene svg').getAttribute('data-fixed-surroundings'),'C01');results.push('Service worker installed; Highfield career reloads with fixed surroundings while offline.');await page.context().setOffline(false);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);fs.writeFileSync(root+'/review/browser-checks.json',JSON.stringify({results,errors,missing},null,2));console.log(JSON.stringify({results,errors,missing},null,2));
}finally{await browser.close();server.close();}
